project:
  type: website
  pre-render: "R/01_data.R"

website:
  title: "LeGeND Dynasty"
  favicon: "legend-family-icon.png"
  navbar:
    logo: "legend-family-icon.png"
    left:
      - href: index.qmd
        text: Activity
      - href: boat.qmd
        text: "Boat Defense"
      - href: cards.qmd
        text: Cards
      - href: war.qmd
        text: "War"
      - href: decks_used.qmd
        text: "Decks Used"
      - href: event.qmd
        text: "Events"
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
