project:
  type: website

website:
  title: "LeGeND Dynasty"
  navbar:
    left:
      - href: index.qmd
        text: Activity
      - href: cards.qmd
        text: Cards
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



