---
title: "Activity"
date: now
execute: 
  echo: false
---

```{r}
#| label: setup
suppressPackageStartupMessages({library(here)})
source(here('R/00_setup.R'))
```

```{r}
#| label: clan
clan <- read_csv(here('data/clan.csv'), 
                 #col_types = cols(.default = col_character()),
                 show_col_types = FALSE)
```

```{r}
#| label: players
players <- read_csv(here('data/players.csv'), 
                  #col_types = cols(.default = col_character()),
                  show_col_types = FALSE)
```

```{r}
#| label: decks_used
decks_used <- read_csv(here('data/decks_used.csv'), 
                  #col_types = cols(.default = col_character()),
                  show_col_types = FALSE)
deck_keep <- max(str_extract(names(decks_used), '\\d+'), na.rm = TRUE)

decks_used <- decks_used |> 
  select(tag, matches(deck_keep))

decks_used <- decks_used |>
  rowwise() |> 
  mutate(
    total_decks_used = sum(c_across(starts_with('decks_used_')))
  ) |> 
  ungroup()
```

```{r}
#| label: war
war <- read_csv(here('data/war.csv'), 
                  #col_types = cols(.default = col_character()),
                  show_col_types = FALSE)

war_keep <- max(str_extract(names(war), '\\d+'), na.rm = TRUE)

war <- war |> 
  select(tag, matches(war_keep))

war <- war |>
  rowwise() |> 
  mutate(
    total_fame = sum(c_across(starts_with('fame_'))),
    avg_fame = as.integer(mean(replace_na(c_across(starts_with('fame_'))), 0))
  ) |> 
  ungroup()
```


:::{.column-page}
```{r}
#| label: table
#| warning: false
clan |> 
  select(starts_with('player')) |>
  rename_with(.fn = \(x) str_sub(x, start = 8)) |> 
  select(-exp_level, -clan_rank, -previous_clan_rank, -starts_with('arena'), -clan_chest_points) |> 
  mutate(
    last_seen_flag = time_min(last_seen) > (48 * 60),
    last_seen = time_short(last_seen)
  ) |> 
  relocate(name, tag, last_seen, role, trophies, starts_with('donations')) |> 
  left_join(
    players |> select(tag, war_day_wins, elite, maxed, legendary, gold, silver, bronze),
    by = 'tag'
  ) |> 
  left_join(
    war, 
    by = 'tag'
  ) |> 
  left_join(
    decks_used, 
    by = 'tag'
  ) |> 
  gt() |> 
  tab_spanner(label = 'Player', columns = c(name, tag)) |> 
  tab_spanner(label = 'Donations', columns = starts_with('donations')) |> 
  tab_spanner(label = 'Card Levels', columns = c(elite, maxed, legendary, gold, silver, bronze)) |> 
  tab_spanner(label = 'War', columns = starts_with('fame_')) |> 
  tab_spanner(label = 'Decks Used', columns = starts_with('decks_used_')) |> 
  cols_label(
    name = 'Name',
    tag = 'Tag',
    last_seen = 'Last Seen',
    role = 'Role',
    trophies = 'Trophies',
    donations = 'Don.',
    donations_received = 'Rec.',
    war_day_wins = 'CW1 Wins',
    elite = 'E',
    maxed = 'M',
    legendary = 'L',
    gold = 'G',
    silver = 'S',
    bronze = 'B'
  ) |> 
  cols_label_with(fn = function(x) x |> str_remove('fame_') |> str_remove('decks_used_')) |> 
  cols_hide(last_seen_flag) |> 
  data_color(
    columns = trophies,
    fn = scales::col_numeric(
      palette = c('white', '#b7e1cd'),
      na.color = 'white',
      domain = c(5000, 9000)
    )
  ) |> 
  data_color(
    columns = donations,
    fn = function(x) scales::col_numeric(
      palette = c('#FFFFFFFF', '#b7e1cd'),
      domain = c(0, 200)
    )(scales::oob_squish(x, c(0, 200)))
  ) |> 
  data_color(
    columns = last_seen_flag,
    target_columns = last_seen,
    method = 'factor',
    palette = c('#FFFFFFFF', '#982649')
  ) |> 
  opt_table_font(
    font = google_font('Martel Sans')
  )

```
:::




